---
title: "Esplorazione dei dati"
description: >
  Learn how to set up search for your pkgdown site using 
  [DocSearch](https://community.algolia.com/docsearch/) from Algolia.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data_Discovery}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduzione

La funzione `getCapability()` permette innanzitutto di restituire le diverse coverage offerte dal servizio di Rasdaman di ARPA LOMBARDIA.
<p style="display:inline; font-style: italic; color:gray"> [Utilizza la funzione ***GetCapabilities*** del WCS] </p>
<br>

Attraverso le seguenti funzioni è invece possibile interrogare i metadati (ottenere descrizione e alcune proprietà) di una specifica coverage selezionata:
<p style="display:inline; font-style: italic; color:gray"> [Utilizzano la funzione ***DescribeCoverage*** del servizio WCS] </p>

* `coverage_get_bands()`
* `coverage_get_bounding_box()`
* `coverage_get_coordinate_reference()`
* `coverage_get_coordsys()`
* `coverage_get_resolution()`
* `coverage_get_temporal_extent()`
* `coverage_get_timestamps()`


## Importazione delle librerie necessarie

```r
library(myCubeR)
```

## Utilizzo delle funzioni implementate
Richiedere l'elenco delle Coverage/Servizi WCS offerti dal server Rasdaman:

```r
coverages<-getCapability()
```

```r
coverages
#[1]  "rh_ana"    "rh_idi"    "t2m_idi"   "enne_mean" "t2m_ana"   "prec_ana"  "pwet_idi"  "bui"       "fwi"       "ffmc"      "pdry_idi" 
#[12] "dmc"       "rh_hdx"    "isi"       "dc"        "t2m_bkg"   
```

Scegliere una coverage (in questo caso *rh_ana*):

```r
coverage<-getCapability()[1]
```

```r
coverage
#[1] "rh_ana" 
```


Per la coverage selezionata (*rh_ana*) è possibile:

Richiedere gli "assi" che descrivono i Datacube (solitamente X,Y e come terza variabile/asse il tempo):

```r
axes<-coverage_get_coordsys(coverage = coverage)
```

```r
axes
#[1] "ansi" "E"    "N" 
```

Richiedere il sistema di riferimento della coverage

```r
ref_sys=coverage_get_coordinate_reference(coverage=coverage)
```
```r
ref_sys
#[1] "32632"
```

Richiedere "l'estensione temporale" della Coverage

```r
temp_ext=coverage_get_temporal_extent(coverage=coverage)
```
```r
temp_ext
#[1] "2020-05-18T12:00:00.000Z" "2020-11-10T06:00:00.000Z"
```

Richiedere l'entensione (BBOX) spaziale della Coverage

```r
bb_box=coverage_get_bounding_box(coverage=coverage)
```
```r
bb_box
#[1] "436000"  "687000"  "4918000" "5167000"
```

Richiedere la risoluzione spaziale della Coverage

```r
res=coverage_get_resolution(coverage=coverage)
```
```r
res
#[1] 1000
```

Richiedere il nome delle bande (di default per Rasdaman di ARPA LOMBARDIA la variabile principale viene nominata *field_1*. Es per rh_ana corrisponde a......)

```r
bands<-coverage_get_bands(coverage = coverage)
```
```r
bands
#[1] "field_1"
```

Richiedere tutte i "timestamp"/le date per cui sono disponibili i raster che costruiscono il Datacube

```r
time_stamp=coverage_get_timestamps(coverage=coverage)
```
```r
time_stamp
#[1] "2020-05-18T12:00:00.000Z" "2020-05-18T13:00:00.000Z" "2020-05-18T14:00:00.000Z" "2020-05-18T15:00:00.000Z" "2020-05-18T16:00:00.000Z"
#[6] "2020-05-18T17:00:00.000Z" "2020-05-18T18:00:00.000Z" "2020-05-18T19:00:00.000Z" "2020-05-18T20:00:00.000Z" "2020-05-18T21:00:00.000Z"
# ................

print(paste("Un totale di",length(time_stamp), "dati"))
#[1] "Un totale di 4133 dati"
```